CREATE TABLE IF NOT EXISTS SALESMAN (
    S_ID TEXT PRIMARY KEY,
    NAME TEXT,
    CITY TEXT,
    COMMISSION REAL  -- Ensure spelling is correct
);

INSERT INTO SALESMAN (S_ID, NAME, CITY, COMMISSION) VALUES 
    ('12', 'JOHN', 'PUNE', 0.15),
    ('13', 'ROLFE', 'MUMBAI', 0.9),
    ('14', 'HARRY', 'NEW DELHI', 0.7),
    ('15', 'MARK', 'HYDERABAD', 0.6),
    ('16', 'NOBITA', 'MOSCOW', 0.33);

CREATE TABLE IF NOT EXISTS CUSTOMER (
    C_ID TEXT,
    C_NAME TEXT PRIMARY KEY,
    CITY TEXT,
    S_ID TEXT,
    FOREIGN KEY (S_ID) REFERENCES SALESMAN(S_ID)
);

INSERT INTO CUSTOMER (C_ID, C_NAME, CITY, S_ID) VALUES
    ('100', 'RAJVEER', 'PUNE', '12'),
    ('101', 'ANAY', 'DELHI', '13'),
    ('102', 'SHIV', 'LUCKNOW', '14');

CREATE TABLE IF NOT EXISTS ORDERS (
    O_NUMBER TEXT PRIMARY KEY,
    P_AMOUNT REAL,
    O_DATE TEXT,
    C_ID TEXT,
    S_ID TEXT,
    FOREIGN KEY (C_ID) REFERENCES CUSTOMER(C_ID),
    FOREIGN KEY (S_ID) REFERENCES SALESMAN(S_ID)
);

INSERT INTO ORDERS (O_NUMBER, P_AMOUNT, O_DATE, C_ID, S_ID) VALUES
    ('1', 1000, '2024-03-12', '100', '12'),
    ('2', 1200, '2024-02-13', '101', '13'),
    ('3', 1800, '2023-09-10', '102', '14');

-- 1. Join CUSTOMER and SALESMAN on CITY
SELECT CUSTOMER.C_NAME, SALESMAN.NAME, SALESMAN.CITY 
FROM CUSTOMER 
JOIN SALESMAN ON CUSTOMER.CITY = SALESMAN.CITY;

-- 2. Join CUSTOMER and SALESMAN on S_ID
SELECT CUSTOMER.C_NAME, SALESMAN.NAME 
FROM CUSTOMER
JOIN SALESMAN ON CUSTOMER.S_ID = SALESMAN.S_ID;

-- 3. Join ORDERS, CUSTOMER, and SALESMAN, filtering on CITY
SELECT ORDERS.O_NUMBER, CUSTOMER.C_NAME, ORDERS.C_ID, ORDERS.S_ID
FROM ORDERS
JOIN CUSTOMER ON ORDERS.C_ID = CUSTOMER.C_ID
JOIN SALESMAN ON ORDERS.S_ID = SALESMAN.S_ID
WHERE CUSTOMER.CITY <> SALESMAN.CITY;

-- 4. Select ORDERS and CUSTOMER
SELECT ORDERS.O_NUMBER, CUSTOMER.C_NAME
FROM ORDERS 
JOIN CUSTOMER ON ORDERS.C_ID = CUSTOMER.C_ID;

-- 5. Select CUSTOMER, CITY, SALESMAN, and COMMISSION
SELECT CUSTOMER.C_NAME AS "CUSTOMER", 
       CUSTOMER.CITY AS "CITY",
       SALESMAN.NAME AS "SALESMAN",
       SALESMAN.COMMISSION
FROM CUSTOMER
JOIN SALESMAN ON CUSTOMER.S_ID = SALESMAN.S_ID
WHERE SALESMAN.COMMISSION BETWEEN 0.15 AND 0.9;  -- This should be valid now

-- 6. Corrected SELECT statement with the missing comma
SELECT * 
FROM CUSTOMER 
JOIN ORDERS ON CUSTOMER.C_ID = ORDERS.C_ID
WHERE ORDERS.O_DATE = '2024-02-13';
